base:
  mass: 0.8                 # Base mass in Kg
  x_size: 0.109067             # Dimension in x axis
  y_size: 0.1               # Dimension in y axis
  z_size: 0.0465              # Dimension in z axis
  mesh: 'battery_chassis.stl' # Name of the mesh files. Leave it empty ('') to have a white base.
