wheel:
  mass: 0.5        # Wheel mass in Kg
  radius: 0.015     # Wheel radius in m
  mesh: 'caster_wheel.stl'          # Name of the mesh files. Leave it empty ('') to have a red wheel
  x_offset: 0.035
  dx: -0.016  # ${-caster_base_size/2.0*0.8}
  dy: -1
  dz: -0.04
