wheel:
  mass: 0.5        # Wheel mass in Kg
  radius: 0.010747
  size:
    x: 0.032
    y: 0.032
    z: 0.02
  mesh: 'caster_wheel.stl'          # Name of the mesh files. Leave it empty ('') to have a red wheel
  dx: -0.0754  
  dy: 0.0
  dz: -0.003
