base:
  #mass: 0.8               # Base mass in Kg
  mass: 6.0               # We use a bigger mass to be able to run with Gazebo ROS Control.
  x_size: 0.195           # Dimension in x axis
  y_size: 0.08            # Dimension in y axis
  z_size: 0.005           # Dimension in z axis
  mesh: 'chassis.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
